### ISSUE TITLE
allaudit file info break

### ISSUE THREAD

**Issue by Creutzx** [Creutzx/ContinuousRprocessing#3]
Breaks Here:

initially was from the file path being too long, then moved the edited RData files to a location with a shorter path. After that, I get this error when reading these in. I've gone through the AUDIT_INFO files as well...

https://github.com/Creutzx/ContinuousRprocessing/blob/74e3c9dfb44d4510c3dea1dd7f419d1c64968409/04_CnPlotsStatsSummaries.R#L63

![image](https://user-images.githubusercontent.com/32490475/61495806-eda4ad80-a96e-11e9-99b6-4fc0e7526d23.png)

**Comment by TravisPritchardODEQ** [comment]
Look to see if the filename has an errant underscore. If the station description has an underscore, we get this error.

**Comment by Creutzx** [comment]
Thanks, that was something I wanted to check with you about, and looking at [issue #2](https://github.com/Creutzx/ContinuousRprocessing/issues/2#issue-469978482), the R script apparently replaces the / with an underscore, which gets brought into the filename. That happens a couple of times in this input file:

![image](https://user-images.githubusercontent.com/32490475/61548165-e24e9200-aa01-11e9-9e0b-9fe0cd92e123.png)

There were other special characters too that might be at issue, for example:

![image](https://user-images.githubusercontent.com/32490475/61547530-6a339c80-aa00-11e9-8b99-8afa66a6f30f.png)

I was going to fix these with additional gsub lines, but it almost looks like that would be better to do when it's still in the excel spreadsheet.

**Comment by SteveHansonODEQ** [comment]
I believe later scripts parse out filenames by the underscore character in order to get logger number, site ID, etc..  So underscores should not be present in site descriptions.

Steve Hanson
DEQ-Lab WQM
W:503.693.5737
C: 971.806.2425

**Comment by Creutzx** [comment]
Thanks!
